# Generated by Django 3.1.1 on 2020-12-27 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coop_company',
            field=models.CharField(blank=True, max_length=250, verbose_name='First Co-op Company Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='coop_position',
            field=models.CharField(blank=True, max_length=250, verbose_name='First Co-op Position Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='instructor',
            field=models.CharField(choices=[('carpenter-oliveria', 'Heather Carpenter-Oliveria'), ('looney', 'Georgia Looney'), ('lu', 'Lucy Lu'), ('macilroy', 'Robin MacIlroy'), ('mockler', 'Sarah Mockler'), ('parker', 'Kevin Parker'), ('ziegler', 'Nathanial Ziegler'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20, verbose_name='Instructor Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_interviewees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('BSME', 'Mechanical Engineering'), ('BSIE', 'Mechanical Engineering'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20, verbose_name='Major'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_interview_slots',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=1, verbose_name='Interview Slots'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('interviewer', 'Interviewer'), ('interviewee', 'Interviewee'), ('unspecified', 'Unspecified')], default='unspecified', max_length=15, verbose_name='Interviewee/Interviewer'),
        ),
    ]
