# Generated by Django 3.1.2 on 2020-12-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('coop_company', models.CharField(max_length=200)),
                ('coop_position', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='Northeastern Email Address')),
                ('date_registered', models.DateField()),
                ('instructor', models.CharField(max_length=200)),
                ('interview_slots', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='Northeastern Email Address')),
                ('date_registered', models.DateField()),
                ('instructor', models.CharField(max_length=200)),
                ('interview_booked', models.BooleanField(default=False)),
                ('Interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.interviewer')),
            ],
        ),
    ]
